<?php

/*Controls saving process of options in dashboard settings. This file is subordinate to upboption.php*/

	$selectedTabId = 1;

	if(isset($_REQUEST['submit']))

	{

		$selectedTabId = 5;

		if($_REQUEST['recaptcha']=="yes")
		{
			mytable_add_option( 'upb_recaptcha', 'yes');
		}
		else
		{
			mytable_add_option( 'upb_recaptcha', 'no');
		}
		
		if($_REQUEST['upb_public_key'])

		{

			mytable_add_option( 'upb_public_key', $_REQUEST['upb_public_key'] );

		}

		if($_REQUEST['upb_private_key'])

		{

			mytable_add_option( 'upb_private_key', $_REQUEST['upb_private_key'] );	

		}
		
		if($_REQUEST['autogeneratedepass']=="yes")

		{

			mytable_add_option( 'upb_autogeneratedepass', 'yes');

		}

		else

		{

			mytable_add_option( 'upb_autogeneratedepass', 'no');

		}

		

		/* saved facebook setting data start */

		if($_REQUEST['facebook_login'])

		{

			mytable_add_option( 'upb_facebook_login', $_REQUEST['facebook_login'] );

		}

		if($_REQUEST['facebook_app_id'])

		{

			mytable_add_option( 'upb_facebook_app_id', $_REQUEST['facebook_app_id'] );

		}

		if($_REQUEST['facebook_app_secret'])

		{

			mytable_add_option( 'upb_facebook_app_secret', $_REQUEST['facebook_app_secret'] );	

		}

		/* saved facebook setting data end */

		

		if($_REQUEST['max_results'])

		{

			mytable_add_option( 'upb_profile_max_resutls', $_REQUEST['max_results'] );

		}



		if($_REQUEST['profilelistview'] == "table")

		{

			mytable_add_option( 'upb_profile_list_view', 'table');

		}

		else

		{

			mytable_add_option( 'upb_profile_list_view', 'box');



			if($_REQUEST['box_width'] == "1")

			{

				mytable_add_option( 'upb_profile_list_column', '1');

			}

			else if($_REQUEST['box_width'] == "2")

			{

				mytable_add_option( 'upb_profile_list_column', '2');

			}

			else if($_REQUEST['box_width'] == "3")

			{

				mytable_add_option( 'upb_profile_list_column', '3');

			}

			else

			{

				mytable_add_option( 'upb_profile_list_column', '4');

			}

		}

	}



	if(isset($_REQUEST['submit1']))

	{

		$selectedTabId = 3;

		if($_REQUEST['adminshowhide']=="yes")

		{

			mytable_add_option( 'upb_adminshowhide', 'yes');

		}

		else

		{

			mytable_add_option( 'upb_adminshowhide', 'no');

		}



		if($_REQUEST['editorshowhide']=="yes")

		{

			mytable_add_option( 'upb_editorshowhide', 'yes');

		}

		else

		{

			mytable_add_option( 'upb_editorshowhide', 'no');

		}

		

		if($_REQUEST['authorshowhide']=="yes")

		{

			mytable_add_option( 'upb_authorshowhide', 'yes');

		}

		else

		{

			mytable_add_option( 'upb_authorshowhide', 'no');

		}



		if($_REQUEST['contributorshowhide']=="yes")

		{

			mytable_add_option( 'upb_contributorshowhide', 'yes');

		}

		else

		{

			mytable_add_option( 'upb_contributorshowhide', 'no');

		}



		if($_REQUEST['subscribershowhide']=="yes")

		{

			mytable_add_option( 'upb_subscribershowhide', 'yes');

		}

		else

		{

			mytable_add_option( 'upb_subscribershowhide', 'no');

		}

	}



	if(isset($_REQUEST['RegCustomSubmit']))

	{



		$selectedTabId = 4;	

		if($_REQUEST['usernameshowhide']=="") $_REQUEST['usernameshowhide']='no';

		if($_REQUEST['nicknameshowhide']=="") $_REQUEST['nicknameshowhide']='no';

		if($_REQUEST['emailshowhide']=="") $_REQUEST['emailshowhide']='no';

		if($_REQUEST['websiteshowhide']=="") $_REQUEST['websiteshowhide']='no';

		if($_REQUEST['aimshowhide']=="") $_REQUEST['aimshowhide']='no';

		if($_REQUEST['yahooimshowhide']=="") $_REQUEST['yahooimshowhide']='no';

		if($_REQUEST['jabbergoogletalkshowhide']=="") $_REQUEST['jabbergoogletalkshowhide']='no';

		if($_REQUEST['aboutmeshowhide']=="") $_REQUEST['aboutmeshowhide']='no';

		if($_REQUEST['postshowhide']=="") $_REQUEST['postshowhide']='no';

		

		mytable_add_option( 'upb_usernameshowhide', $_REQUEST['usernameshowhide']);

		mytable_add_option( 'upb_nicknameshowhide', $_REQUEST['nicknameshowhide']);

		mytable_add_option( 'upb_emailshowhide', $_REQUEST['emailshowhide']);

		mytable_add_option( 'upb_websiteshowhide', $_REQUEST['websiteshowhide']);

		mytable_add_option( 'upb_aimshowhide', $_REQUEST['aimshowhide']);

		mytable_add_option( 'upb_yahooimshowhide', $_REQUEST['yahooimshowhide']);

		mytable_add_option( 'upb_jabbergoogletalkshowhide', $_REQUEST['jabbergoogletalkshowhide']);

		mytable_add_option( 'upb_biographicalinfoshowhide', $_REQUEST['aboutmeshowhide']);

		mytable_add_option( 'upb_postshowhide', $_REQUEST['postshowhide']);

	}

	

	if(isset($_REQUEST['personalization']))

	{



		$selectedTabId = 2;	

		mytable_add_option( 'Registration_Custom_Text', $_REQUEST['RegCustomText']);

		

	}



	function mytable_add_option($fieldname,$value)

	{

		global $wpdb;

		$upb_option=$wpdb->prefix."upb_option";

		$update="update $upb_option set value='".$value."' where fieldname='".$fieldname."'";

		$wpdb->query($update);

	}



	function checkfieldname($fieldname,$value)

	{

		global $wpdb;

		$upb_option=$wpdb->prefix."upb_option";

		$select="select value from $upb_option where fieldname='".$fieldname."'and value='".$value."'";

		$data = $wpdb->get_var($select);



		if($data==$value)

		{

			return true;

		}

		else

		{

			return false;

		}

	}

?>